name: Github Pages Deploy

on:
  push:
    branches:
      - "master"
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        working-directory: ./
        run: npm install && npm run gh-build  && cp dist/github-angular/index.html dist/github-angular/404.html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist/github-angular # The folder the action should deploy.        